<?php

namespace Database\Seeders;

use App\Models\Movie;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MovieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Movie::query()->delete();

        $movies = [
            [
                'title' => 'Dune: Part Two',
                'original_title' => 'Dune: Part Two',
                'description' => 'Một câu chuyện ép khí hậu và chiến lược giữa các gia tộc trên một hành tinh khô cằn.',
                'duration_minutes' => 166,
                'release_date' => '2024-02-29',
                'end_date' => '2026-12-31',
                'age_rating' => 'T13',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Denis Villeneuve',
                'cast' => 'Timothée Chalamet, Zendaya, Rebecca Ferguson',
                'poster_url' => 'uploads/movies/dune-part-two-poster.svg',
                'banner_url' => 'uploads/movies/dune-part-two-banner.svg',
                'trailer_url' => 'https://youtu.be/Way9Dexny3w',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Inside Out 2',
                'original_title' => 'Inside Out 2',
                'description' => 'Riley bước vào tuổi teen và đón nhận các cảm xúc mới trong một cuộc hành trình đầy màu sắc.',
                'duration_minutes' => 96,
                'release_date' => '2024-06-14',
                'end_date' => '2026-12-31',
                'age_rating' => 'P',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Kelsey Mann',
                'cast' => 'Amy Poehler, Maya Hawke, Kensington Tallman',
                'poster_url' => 'uploads/movies/inside-out-2-poster.svg',
                'banner_url' => 'uploads/movies/inside-out-2-banner.svg',
                'trailer_url' => 'https://youtu.be/seMwpP0yeu4',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Godzilla x Kong: The New Empire',
                'original_title' => 'Godzilla x Kong: The New Empire',
                'description' => 'Hai kẻ khổng lồ cùng đối mặt với một thế lực mới đe dọa cả thế giới.',
                'duration_minutes' => 115,
                'release_date' => '2024-03-29',
                'end_date' => '2026-12-31',
                'age_rating' => 'T13',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Adam Wingard',
                'cast' => 'Rebecca Hall, Brian Tyree Henry, Dan Stevens',
                'poster_url' => 'uploads/movies/godzilla-x-kong-poster.svg',
                'banner_url' => 'uploads/movies/godzilla-x-kong-banner.svg',
                'trailer_url' => 'https://youtu.be/qqrpMRDuZy8',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Venom: The Last Dance',
                'original_title' => 'Venom: The Last Dance',
                'description' => 'Eddie Brock và Venom phải chạy trốn khỏi những thế lực đen tối đang truy đuổi.',
                'duration_minutes' => 109,
                'release_date' => '2024-10-25',
                'end_date' => '2026-12-31',
                'age_rating' => 'T13',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Kelly Marcel',
                'cast' => 'Tom Hardy, Chiwetel Ejiofor, Juno Temple',
                'poster_url' => 'uploads/movies/venom-last-dance-poster.svg',
                'banner_url' => 'uploads/movies/venom-last-dance-banner.svg',
                'trailer_url' => 'https://youtu.be/XYx8fxn0gY8',
                'status' => 'COMING_SOON',
            ],
            [
                'title' => 'Deadpool & Wolverine',
                'original_title' => 'Deadpool & Wolverine',
                'description' => 'Deadpool và Wolverine hợp tác trong một cuộc phiêu lưu siêu anh hùng đầy lố bịch.',
                'duration_minutes' => 127,
                'release_date' => '2024-07-26',
                'end_date' => '2026-12-31',
                'age_rating' => 'T16',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Shawn Levy',
                'cast' => 'Ryan Reynolds, Hugh Jackman, Emma Corrin',
                'poster_url' => 'uploads/movies/deadpool-wolverine-poster.svg',
                'banner_url' => 'uploads/movies/deadpool-wolverine-banner.svg',
                'trailer_url' => 'https://youtu.be/73_1biulkYk',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Kung Fu Panda 4',
                'original_title' => 'Kung Fu Panda 4',
                'description' => 'Po phải chọn một người kế nhiệm và đối đầu với kẻ thù mới trong thế giới võ thuật.',
                'duration_minutes' => 94,
                'release_date' => '2024-03-08',
                'end_date' => '2026-12-31',
                'age_rating' => 'P',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Mike Mitchell',
                'cast' => 'Jack Black, Awkwafina, Viola Davis',
                'poster_url' => 'uploads/movies/kung-fu-panda-4-poster.svg',
                'banner_url' => 'uploads/movies/kung-fu-panda-4-banner.svg',
                'trailer_url' => 'https://youtu.be/_inKs4eeHiI',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'The Garfield Movie',
                'original_title' => 'The Garfield Movie',
                'description' => 'Garfield bước vào một cuộc phiêu lưu mới với Jon và Odie trong thành phố.',
                'duration_minutes' => 101,
                'release_date' => '2024-05-24',
                'end_date' => '2026-12-31',
                'age_rating' => 'P',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Mark Dindal',
                'cast' => ' Chris Pratt, Samuel L. Jackson, Hannah Waddingham',
                'poster_url' => 'uploads/movies/garfield-movie-poster.svg',
                'banner_url' => 'uploads/movies/garfield-movie-banner.svg',
                'trailer_url' => 'https://youtu.be/3xJqk1P_0jE',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'The Beekeeper',
                'original_title' => 'The Beekeeper',
                'description' => 'Một người đàn ông bí mật với kỹ năng đặc biệt bắt đầu trả thù cho một người bạn cũ.',
                'duration_minutes' => 105,
                'release_date' => '2024-01-12',
                'end_date' => '2026-12-31',
                'age_rating' => 'T16',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'David Ayer',
                'cast' => 'Jason Statham, Emmy Raver-Lampman, Josh Hutcherson',
                'poster_url' => 'uploads/movies/the-beekeeper-poster.svg',
                'banner_url' => 'uploads/movies/the-beekeeper-banner.svg',
                'trailer_url' => 'https://youtu.be/6dI82V0PQSo',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'A Quiet Place: Day One',
                'original_title' => 'A Quiet Place: Day One',
                'description' => 'Một cuộc sống mới bắt đầu trong một thế giới đầy rẫy những sinh vật khát máu.',
                'duration_minutes' => 100,
                'release_date' => '2024-06-28',
                'end_date' => '2026-12-31',
                'age_rating' => 'T13',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Michael Sarnoski',
                'cast' => 'Lupita Nyongo, Joseph Quinn, Djimon Hounsou',
                'poster_url' => 'uploads/movies/a-quiet-place-day-one-poster.svg',
                'banner_url' => 'uploads/movies/a-quiet-place-day-one-banner.svg',
                'trailer_url' => 'https://youtu.be/dM5OC0o6Kxk',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'The Marvels',
                'original_title' => 'The Marvels',
                'description' => 'Ba siêu anh hùng Marvel phải hợp lực chống lại một mối đe dọa vũ trụ.',
                'duration_minutes' => 105,
                'release_date' => '2023-11-10',
                'end_date' => '2026-12-31',
                'age_rating' => 'T13',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Nia DaCosta',
                'cast' => 'Brie Larson, Teyonah Parris, Iman Vellani',
                'poster_url' => 'uploads/movies/the-marvels-poster.svg',
                'banner_url' => 'uploads/movies/the-marvels-banner.svg',
                'trailer_url' => 'https://youtu.be/7U6ZuH5NnD4',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Spider-Man: Across the Spider-Verse',
                'original_title' => 'Spider-Man: Across the Spider-Verse',
                'description' => 'Miles Morales tiếp tục cuộc hành trình giữa nhiều vũ trụ khác nhau.',
                'duration_minutes' => 140,
                'release_date' => '2023-06-02',
                'end_date' => '2026-12-31',
                'age_rating' => 'P',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Joaquim Dos Santos',
                'cast' => 'Shameik Moore, Hailee Steinfeld, Oscar Isaac',
                'poster_url' => 'uploads/movies/spider-verse-poster.svg',
                'banner_url' => 'uploads/movies/spider-verse-banner.svg',
                'trailer_url' => 'https://youtu.be/shW9i6k8cB0',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Elemental',
                'original_title' => 'Elemental',
                'description' => 'Một câu chuyện tình cảm giữa hai thế giới nguyên tố khác biệt.',
                'duration_minutes' => 101,
                'release_date' => '2023-06-16',
                'end_date' => '2026-12-31',
                'age_rating' => 'P',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Peter Sohn',
                'cast' => 'Leah Lewis, Mamoudou Athie, Ronnie del Carmen',
                'poster_url' => 'uploads/movies/elemental-poster.svg',
                'banner_url' => 'uploads/movies/elemental-banner.svg',
                'trailer_url' => 'https://youtu.be/BOqFRHkXx0g',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Barbie',
                'original_title' => 'Barbie',
                'description' => 'Barbie và Ken bước vào một cuộc phiêu lưu đầy trí tuệ và màu sắc.',
                'duration_minutes' => 114,
                'release_date' => '2023-07-21',
                'end_date' => '2026-12-31',
                'age_rating' => 'T13',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Greta Gerwig',
                'cast' => 'Margot Robbie, Ryan Gosling, Kate McKinnon',
                'poster_url' => 'uploads/movies/barbie-poster.svg',
                'banner_url' => 'uploads/movies/barbie-banner.svg',
                'trailer_url' => 'https://youtu.be/pBk4NYhWNMM',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Oppenheimer',
                'original_title' => 'Oppenheimer',
                'description' => 'Câu chuyện về một trong những nhà khoa học có ảnh hưởng lớn nhất trong lịch sử.',
                'duration_minutes' => 180,
                'release_date' => '2023-07-21',
                'end_date' => '2026-12-31',
                'age_rating' => 'T16',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Christopher Nolan',
                'cast' => 'Cillian Murphy, Emily Blunt, Robert Downey Jr.',
                'poster_url' => 'uploads/movies/oppenheimer-poster.svg',
                'banner_url' => 'uploads/movies/oppenheimer-banner.svg',
                'trailer_url' => 'https://youtu.be/uYPbbksJxIg',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'The Nun II',
                'original_title' => 'The Nun II',
                'description' => 'Một phần tiếp nối đầy kinh dị về mối đe dọa bí ẩn trong tu viện.',
                'duration_minutes' => 110,
                'release_date' => '2023-09-08',
                'end_date' => '2026-12-31',
                'age_rating' => 'T16',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Michael Chaves',
                'cast' => 'Taissa Farmiga, Bonnie Aarons, Storm Reid',
                'poster_url' => 'uploads/movies/the-nun-2-poster.svg',
                'banner_url' => 'uploads/movies/the-nun-2-banner.svg',
                'trailer_url' => 'https://youtu.be/QF-oyCwaArU',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'John Wick: Chapter 4',
                'original_title' => 'John Wick: Chapter 4',
                'description' => 'John Wick tiếp tục hành trình trả thù với những trận đấu đẫm máu.',
                'duration_minutes' => 169,
                'release_date' => '2023-03-24',
                'end_date' => '2026-12-31',
                'age_rating' => 'T16',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Chad Stahelski',
                'cast' => 'Keanu Reeves, Donnie Yen, Ian McShane',
                'poster_url' => 'uploads/movies/john-wick-4-poster.svg',
                'banner_url' => 'uploads/movies/john-wick-4-banner.svg',
                'trailer_url' => 'https://youtu.be/yjRHZEUamCc',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Your Name',
                'original_title' => 'Kimi no Na wa',
                'description' => 'Một câu chuyện lãng mạn và huyền ảo giữa hai thế giới kết nối bằng một lời hứa.',
                'duration_minutes' => 106,
                'release_date' => '2016-08-26',
                'end_date' => '2026-12-31',
                'age_rating' => 'P',
                'language' => 'Japanese',
                'subtitle' => 'Tiếng Việt',
                'country' => 'Japan',
                'director' => 'Makoto Shinkai',
                'cast' => 'Ryunosuke Kamiki, Mone Kamishiraishi',
                'poster_url' => 'uploads/movies/your-name-poster.svg',
                'banner_url' => 'uploads/movies/your-name-banner.svg',
                'trailer_url' => 'https://youtu.be/xU47nhruN-Q',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Doraemon: Nobita and the New Steel Troops',
                'original_title' => 'Doraemon',
                'description' => 'Doraemon và Nobita cùng nhau khám phá một thành phố robot đầy bí ẩn.',
                'duration_minutes' => 111,
                'release_date' => '2020-03-20',
                'end_date' => '2026-12-31',
                'age_rating' => 'P',
                'language' => 'Japanese',
                'subtitle' => 'Tiếng Việt',
                'country' => 'Japan',
                'director' => 'Yukiyo Teramoto',
                'cast' => 'Wasabi Mizuta, Megumi Ōhara, Yumi Kakazu',
                'poster_url' => 'uploads/movies/doraemon-nobita-poster.svg',
                'banner_url' => 'uploads/movies/doraemon-nobita-banner.svg',
                'trailer_url' => 'https://youtu.be/voYtI2lWOss',
                'status' => 'COMING_SOON',
            ],
            [
                'title' => 'The Batman',
                'original_title' => 'The Batman',
                'description' => 'Batman đối đầu với các thủ phạm tội phạm trong thành phố Gotham.',
                'duration_minutes' => 176,
                'release_date' => '2022-03-04',
                'end_date' => '2026-12-31',
                'age_rating' => 'T13',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Matt Reeves',
                'cast' => 'Robert Pattinson, Zoë Kravitz, Colin Farrell',
                'poster_url' => 'uploads/movies/the-batman-poster.svg',
                'banner_url' => 'uploads/movies/the-batman-banner.svg',
                'trailer_url' => 'https://youtu.be/mqqft2x_Aa4',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Mission: Impossible – Dead Reckoning',
                'original_title' => 'Mission: Impossible – Dead Reckoning',
                'description' => 'Ethan Hunt phải ngăn chặn một mối nguy hiểm tầm cỡ toàn cầu.',
                'duration_minutes' => 163,
                'release_date' => '2023-07-14',
                'end_date' => '2026-12-31',
                'age_rating' => 'T13',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Christopher McQuarrie',
                'cast' => 'Tom Cruise, Hayley Atwell, Vanessa Kirby',
                'poster_url' => 'uploads/movies/mission-impossible-poster.svg',
                'banner_url' => 'uploads/movies/mission-impossible-banner.svg',
                'trailer_url' => 'https://youtu.be/avz06PDqDbM',
                'status' => 'NOW_SHOWING',
            ],
        ];

        foreach ($movies as $movie) {
            Movie::create([
                'title' => $movie['title'],
                'slug' => Str::slug($movie['title']),
                'original_title' => $movie['original_title'],
                'description' => $movie['description'],
                'duration_minutes' => $movie['duration_minutes'],
                'release_date' => $movie['release_date'],
                'end_date' => $movie['end_date'],
                'age_rating' => $movie['age_rating'],
                'language' => $movie['language'],
                'subtitle' => $movie['subtitle'],
                'country' => $movie['country'],
                'director' => $movie['director'],
                'cast' => $movie['cast'],
                'poster_url' => $movie['poster_url'],
                'banner_url' => $movie['banner_url'],
                'trailer_url' => $movie['trailer_url'],
                'status' => $movie['status'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
