<?php

namespace Database\Seeders;

use App\Models\Movie;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MovieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Movie::query()->delete();

        $movies = [
            [
                'title' => 'Dune: Part Two',
                'original_title' => 'Dune: Part Two',
                'description' => 'Một câu chuyện ép khí hậu và chiến lược giữa các gia tộc trên một hành tinh khô cằn.',
                'duration_minutes' => 166,
                'release_date' => '2024-02-29',
                'end_date' => '2026-12-31',
                'age_rating' => 'T13',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Denis Villeneuve',
                'cast' => 'Timothée Chalamet, Zendaya, Rebecca Ferguson',
                'poster_url' => 'poster_film/01zWUSHRPFzNwiwP0bcLtM4SBA5KSktx9ZPgcXwD.jpg',
                'banner_url' => 'banner_film/0tlQMJ29LKi4rk7EQjMiUW2Qq4bacoXxiZzPQztV.webp',
                'trailer_url' => 'https://youtu.be/Way9Dexny3w',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Inside Out 2',
                'original_title' => 'Inside Out 2',
                'description' => 'Riley bước vào tuổi teen và đón nhận các cảm xúc mới trong một cuộc hành trình đầy màu sắc.',
                'duration_minutes' => 96,
                'release_date' => '2024-06-14',
                'end_date' => '2026-12-31',
                'age_rating' => 'P',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Kelsey Mann',
                'cast' => 'Amy Poehler, Maya Hawke, Kensington Tallman',
                'poster_url' => 'poster_film/0b6Rctsj4lo1nLOdT3eab30brF2J7iAfJaz5wyrJ.jpg',
                'banner_url' => 'combos/6Rvw2icr8b0zo9DttNPSJjELMbSMg9wfkdlShiGc.png',
                'trailer_url' => 'https://youtu.be/seMwpP0yeu4',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Godzilla x Kong: The New Empire',
                'original_title' => 'Godzilla x Kong: The New Empire',
                'description' => 'Hai kẻ khổng lồ cùng đối mặt với một thế lực mới đe dọa cả thế giới.',
                'duration_minutes' => 115,
                'release_date' => '2024-03-29',
                'end_date' => '2026-12-31',
                'age_rating' => 'T13',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Adam Wingard',
                'cast' => 'Rebecca Hall, Brian Tyree Henry, Dan Stevens',
                'poster_url' => 'poster_film/0qKLj0h5qOZxJANX6gyE5T7XJ14ndZovYKOcw6Tb.jpg',
                'banner_url' => 'combos/7prbudM7FrDgWj78c6HAp0fKD1bgiQayhQqGvBe8.png',
                'trailer_url' => 'https://youtu.be/qqrpMRDuZy8',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Venom: The Last Dance',
                'original_title' => 'Venom: The Last Dance',
                'description' => 'Eddie Brock và Venom phải chạy trốn khỏi những thế lực đen tối đang truy đuổi.',
                'duration_minutes' => 109,
                'release_date' => '2024-10-25',
                'end_date' => '2026-12-31',
                'age_rating' => 'T13',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Kelly Marcel',
                'cast' => 'Tom Hardy, Chiwetel Ejiofor, Juno Temple',
                'poster_url' => 'poster_film/4ALnw2B1JtXP3yaeyy3LNDPGhGswRiTqxtLoSWws.jpg',
                'banner_url' => 'combos/9iJZFyyGXksNKRZTMYOFWWK88GtCZbPQtpMiNbkH.png',
                'trailer_url' => 'https://youtu.be/XYx8fxn0gY8',
                'status' => 'COMING_SOON',
            ],
            [
                'title' => 'Deadpool & Wolverine',
                'original_title' => 'Deadpool & Wolverine',
                'description' => 'Deadpool và Wolverine hợp tác trong một cuộc phiêu lưu siêu anh hùng đầy lố bịch.',
                'duration_minutes' => 127,
                'release_date' => '2024-07-26',
                'end_date' => '2026-12-31',
                'age_rating' => 'T16',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Shawn Levy',
                'cast' => 'Ryan Reynolds, Hugh Jackman, Emma Corrin',
                'poster_url' => 'poster_film/57cwgMsNWGWCCSTp2pT6HNZYt8kE1wDlxTJWy0Yb.jpg',
                'banner_url' => 'combos/BlxKqGc0CxSQLqc0oNswzD0cqM0494o228tcwhEr.png',
                'trailer_url' => 'https://youtu.be/73_1biulkYk',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Kung Fu Panda 4',
                'original_title' => 'Kung Fu Panda 4',
                'description' => 'Po phải chọn một người kế nhiệm và đối đầu với kẻ thù mới trong thế giới võ thuật.',
                'duration_minutes' => 94,
                'release_date' => '2024-03-08',
                'end_date' => '2026-12-31',
                'age_rating' => 'P',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Mike Mitchell',
                'cast' => 'Jack Black, Awkwafina, Viola Davis',
                'poster_url' => 'poster_film/70RSfyhdJBTLhpNqRNwvR2GbZi03TPTya13m6HtZ.jpg',
                'banner_url' => 'combos/bYFoX3iK1aMoqOKk7SReoyeYzJNtPp4iK43sQoue.png',
                'trailer_url' => 'https://youtu.be/_inKs4eeHiI',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'The Garfield Movie',
                'original_title' => 'The Garfield Movie',
                'description' => 'Garfield bước vào một cuộc phiêu lưu mới với Jon và Odie trong thành phố.',
                'duration_minutes' => 101,
                'release_date' => '2024-05-24',
                'end_date' => '2026-12-31',
                'age_rating' => 'P',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Mark Dindal',
                'cast' => 'Chris Pratt, Samuel L. Jackson, Hannah Waddingham',
                'poster_url' => 'poster_film/8vQFVCbpwoJC2m01beYEGcnqFENgRBjC6TyyH6JS.jpg',
                'banner_url' => 'combos/c5bF2oBeOi7G70ecHFu3gLXJst56558ludUeIlQq.png',
                'trailer_url' => 'https://youtu.be/3xJqk1P_0jE',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'The Beekeeper',
                'original_title' => 'The Beekeeper',
                'description' => 'Một người đàn ông bí mật với kỹ năng đặc biệt bắt đầu trả thù cho một người bạn cũ.',
                'duration_minutes' => 105,
                'release_date' => '2024-01-12',
                'end_date' => '2026-12-31',
                'age_rating' => 'T16',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'David Ayer',
                'cast' => 'Jason Statham, Emmy Raver-Lampman, Josh Hutcherson',
                'poster_url' => 'poster_film/93Zaei9FWjYjAC1BJP1ZLKMJpZDWDc0JiTsMHI6k.jpg',
                'banner_url' => 'combos/cZTBmEeJSblIWGmFEBmKSJ7cTfG8qfQkxxj4la5h.png',
                'trailer_url' => 'https://youtu.be/6dI82V0PQSo',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'A Quiet Place: Day One',
                'original_title' => 'A Quiet Place: Day One',
                'description' => 'Một cuộc sống mới bắt đầu trong một thế giới đầy rẫy những sinh vật khát máu.',
                'duration_minutes' => 100,
                'release_date' => '2024-06-28',
                'end_date' => '2026-12-31',
                'age_rating' => 'T13',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Michael Sarnoski',
                'cast' => 'Lupita Nyongo, Joseph Quinn, Djimon Hounsou',
                'poster_url' => 'poster_film/Aqq1WOLKVjraQDt85cCYLkXWzUtUz5A2w9x9uPIu.jpg',
                'banner_url' => 'combos/GKlVs5pnZBHQUTaKx0xgxbEJyG8v2BkvqHi5Xcr5.png',
                'trailer_url' => 'https://youtu.be/dM5OC0o6Kxk',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'The Marvels',
                'original_title' => 'The Marvels',
                'description' => 'Ba siêu anh hùng Marvel phải hợp lực chống lại một mối đe dọa vũ trụ.',
                'duration_minutes' => 105,
                'release_date' => '2023-11-10',
                'end_date' => '2026-12-31',
                'age_rating' => 'T13',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Nia DaCosta',
                'cast' => 'Brie Larson, Teyonah Parris, Iman Vellani',
                'poster_url' => 'poster_film/cn9jrTrinkBwzhRTTatQm22U6yjMi8cgfYyB0Qvs.jpg',
                'banner_url' => 'combos/GUlLuA9qfJxi7US6j5FsvNw0lRdVd4cuI8ihHNQ7.png',
                'trailer_url' => 'https://youtu.be/7U6ZuH5NnD4',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Spider-Man: Across the Spider-Verse',
                'original_title' => 'Spider-Man: Across the Spider-Verse',
                'description' => 'Miles Morales tiếp tục cuộc hành trình giữa nhiều vũ trụ khác nhau.',
                'duration_minutes' => 140,
                'release_date' => '2023-06-02',
                'end_date' => '2026-12-31',
                'age_rating' => 'P',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Joaquim Dos Santos',
                'cast' => 'Shameik Moore, Hailee Steinfeld, Oscar Isaac',
                'poster_url' => 'poster_film/CnegCbkjidm2iFz7vZ5IU71mSVNbq9yOVVbtWIRu.jpg',
                'banner_url' => 'combos/LTJNxVSkofcKm8flCLgcpVwgFVXKouPCUnONi1ZR.png',
                'trailer_url' => 'https://youtu.be/shW9i6k8cB0',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Elemental',
                'original_title' => 'Elemental',
                'description' => 'Một câu chuyện tình cảm giữa hai thế giới nguyên tố khác biệt.',
                'duration_minutes' => 101,
                'release_date' => '2023-06-16',
                'end_date' => '2026-12-31',
                'age_rating' => 'P',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Peter Sohn',
                'cast' => 'Leah Lewis, Mamoudou Athie, Ronnie del Carmen',
                'poster_url' => 'poster_film/ctmcpalgB15M9ALQP0aUs6aH4FXIgN7Rw4iTD9fB.jpg',
                'banner_url' => 'combos/lWMlHveUdKTOMwJs2Hu7xbqnPRnKH7rdbXftMpdU.jpg',
                'trailer_url' => 'https://youtu.be/BOqFRHkXx0g',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Barbie',
                'original_title' => 'Barbie',
                'description' => 'Barbie và Ken bước vào một cuộc phiêu lưu đầy trí tuệ và màu sắc.',
                'duration_minutes' => 114,
                'release_date' => '2023-07-21',
                'end_date' => '2026-12-31',
                'age_rating' => 'T13',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Greta Gerwig',
                'cast' => 'Margot Robbie, Ryan Gosling, Kate McKinnon',
                'poster_url' => 'poster_film/Dx2IvMR63oYyVYX9BJYXm1qT1psT4BGKWsJ1I2Cf.jpg',
                'banner_url' => 'combos/mOa29JSIv1jTBO0OoAJv3THDuYWFbUCknToN9Ykc.jpg',
                'trailer_url' => 'https://youtu.be/pBk4NYhWNMM',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Oppenheimer',
                'original_title' => 'Oppenheimer',
                'description' => 'Câu chuyện về một trong những nhà khoa học có ảnh hưởng lớn nhất trong lịch sử.',
                'duration_minutes' => 180,
                'release_date' => '2023-07-21',
                'end_date' => '2026-12-31',
                'age_rating' => 'T16',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Christopher Nolan',
                'cast' => 'Cillian Murphy, Emily Blunt, Robert Downey Jr.',
                'poster_url' => 'poster_film/Eq0YzEfJioJX6YLDa0luKEybaEq5SsEdVnDxpyY3.jpg',
                'banner_url' => 'combos/pFAvQCPUPA01b4jmRIUACJvD44w7mXTAanGZhZGs.png',
                'trailer_url' => 'https://youtu.be/uYPbbksJxIg',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'The Nun II',
                'original_title' => 'The Nun II',
                'description' => 'Một phần tiếp nối đầy kinh dị về mối đe dọa bí ẩn trong tu viện.',
                'duration_minutes' => 110,
                'release_date' => '2023-09-08',
                'end_date' => '2026-12-31',
                'age_rating' => 'T16',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Michael Chaves',
                'cast' => 'Taissa Farmiga, Bonnie Aarons, Storm Reid',
                'poster_url' => 'poster_film/ExxOqbXRorOZY93Hq14PQ0Ize1AUeU1vFMZgki4A.jpg',
                'banner_url' => 'combos/PuslwX1Skk9opLphmw6tqQhG9bF6q6WvCvi6kx5y.jpg',
                'trailer_url' => 'https://youtu.be/QF-oyCwaArU',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'John Wick: Chapter 4',
                'original_title' => 'John Wick: Chapter 4',
                'description' => 'John Wick tiếp tục hành trình trả thù với những trận đấu đẫm máu.',
                'duration_minutes' => 169,
                'release_date' => '2023-03-24',
                'end_date' => '2026-12-31',
                'age_rating' => 'T16',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Chad Stahelski',
                'cast' => 'Keanu Reeves, Donnie Yen, Ian McShane',
                'poster_url' => 'poster_film/f4UGVRFGZkN5wxAjDZ6pXaGflZbYXtMalm1PMNVo.jpg',
                'banner_url' => 'combos/QPUdKrHFLnytbaqGcvnQBVGsYp25zI29BDXJyLx8.png',
                'trailer_url' => 'https://youtu.be/yjRHZEUamCc',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Your Name',
                'original_title' => 'Kimi no Na wa',
                'description' => 'Một câu chuyện lãng mạn và huyền ảo giữa hai thế giới kết nối bằng một lời hứa.',
                'duration_minutes' => 106,
                'release_date' => '2016-08-26',
                'end_date' => '2026-12-31',
                'age_rating' => 'P',
                'language' => 'Japanese',
                'subtitle' => 'Tiếng Việt',
                'country' => 'Japan',
                'director' => 'Makoto Shinkai',
                'cast' => 'Ryunosuke Kamiki, Mone Kamishiraishi',
                'poster_url' => 'poster_film/GVCckepQlSpJBrkWBD1hW9yhljCsuupFLwsaXZMD.jpg',
                'banner_url' => 'combos/r0CenXPFQtPS82zlB2c7kRosKdDd8vYtLAHOyZ52.png',
                'trailer_url' => 'https://youtu.be/xU47nhruN-Q',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Doraemon: Nobita and the New Steel Troops',
                'original_title' => 'Doraemon',
                'description' => 'Doraemon và Nobita cùng nhau khám phá một thành phố robot đầy bí ẩn.',
                'duration_minutes' => 111,
                'release_date' => '2020-03-20',
                'end_date' => '2026-12-31',
                'age_rating' => 'P',
                'language' => 'Japanese',
                'subtitle' => 'Tiếng Việt',
                'country' => 'Japan',
                'director' => 'Yukiyo Teramoto',
                'cast' => 'Wasabi Mizuta, Megumi Ōhara, Yumi Kakazu',
                'poster_url' => 'poster_film/g9rfVTFdNUi4HIYOCmSkDvTiNbgODGKu4mK6yT4t.jpg',
                'banner_url' => 'combos/ryfXq32QQmCh9wDvSWDrTwl5YYGza8vAR3HU09LX.png',
                'trailer_url' => 'https://youtu.be/voYtI2lWOss',
                'status' => 'COMING_SOON',
            ],
            [
                'title' => 'The Batman',
                'original_title' => 'The Batman',
                'description' => 'Batman đối đầu với các thủ phạm tội phạm trong thành phố Gotham.',
                'duration_minutes' => 176,
                'release_date' => '2022-03-04',
                'end_date' => '2026-12-31',
                'age_rating' => 'T13',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Matt Reeves',
                'cast' => 'Robert Pattinson, Zoë Kravitz, Colin Farrell',
                'poster_url' => 'poster_film/GVCckepQlSpJBrkWBD1hW9yhljCsuupFLwsaXZMD.jpg',
                'banner_url' => 'banner_film/yI1ILbfn7l3cfLfOOAVUn201zSzujXnDXn7PYKAX.jpg',
                'trailer_url' => 'https://youtu.be/mqqft2x_Aa4',
                'status' => 'NOW_SHOWING',
            ],
            [
                'title' => 'Mission: Impossible – Dead Reckoning',
                'original_title' => 'Mission: Impossible – Dead Reckoning',
                'description' => 'Ethan Hunt phải ngăn chặn một mối nguy hiểm tầm cỡ toàn cầu.',
                'duration_minutes' => 163,
                'release_date' => '2023-07-14',
                'end_date' => '2026-12-31',
                'age_rating' => 'T13',
                'language' => 'English',
                'subtitle' => 'Tiếng Việt',
                'country' => 'USA',
                'director' => 'Christopher McQuarrie',
                'cast' => 'Tom Cruise, Hayley Atwell, Vanessa Kirby',
                'poster_url' => 'poster_film/uinuTxUYmS7LvEXnpdGqjS5T2sz6yB4yZ46S2SSg.jpg',
                'banner_url' => 'combos/TnPur8Lf9kVkY4dX82vByvWF74MVEdEVedU5ddbb.png',
                'trailer_url' => 'https://youtu.be/avz06PDqDbM',
                'status' => 'NOW_SHOWING',
            ],
        ];

        foreach ($movies as $movie) {
            Movie::create([
                'title' => $movie['title'],
                'slug' => Str::slug($movie['title']),
                'original_title' => $movie['original_title'],
                'description' => $movie['description'],
                'duration_minutes' => $movie['duration_minutes'],
                'release_date' => $movie['release_date'],
                'end_date' => $movie['end_date'],
                'age_rating' => $movie['age_rating'],
                'language' => $movie['language'],
                'subtitle' => $movie['subtitle'],
                'country' => $movie['country'],
                'director' => $movie['director'],
                'cast' => $movie['cast'],
                'poster_url' => $movie['poster_url'],
                'banner_url' => $movie['banner_url'],
                'trailer_url' => $movie['trailer_url'],
                'status' => $movie['status'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
